# Generated by Django 5.0.1 on 2025-06-21 19:37

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Τμήματος')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Κωδικός Τμήματος')),
                ('department_type', models.CharField(choices=[('DIRECTION', 'Διεύθυνση'), ('AUTONOMOUS_DIRECTION', 'Αυτοτελής Διεύθυνση'), ('DEPARTMENT', 'Τμήμα'), ('OFFICE', 'Γραφείο')], max_length=30, verbose_name='Τύπος Τμήματος')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('parent_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Γονικό Τμήμα')),
            ],
            options={
                'verbose_name': 'Τμήμα',
                'verbose_name_plural': 'Τμήματα',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, verbose_name='Όνομα')),
                ('last_name', models.CharField(max_length=50, verbose_name='Επίθετο')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Τηλέφωνο')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Αριθμός Μητρώου')),
                ('role', models.CharField(choices=[('employee', 'Υπάλληλος'), ('department_manager', 'Προϊστάμενος Τμήματος'), ('leave_handler', 'Χειριστής Αδειών'), ('administrator', 'Διαχειριστής')], default='employee', max_length=20, verbose_name='Ρόλος')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πρόσληψης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Όνομα Χρήστη')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Προϊστάμενος')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='Τμήμα')),
            ],
            options={
                'verbose_name': 'Χρήστης',
                'verbose_name_plural': 'Χρήστες',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
