# Generated by Django 5.0.1 on 2025-06-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Κωδικός Ρόλου')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Ρόλου')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
            ],
            options={
                'verbose_name': 'Ρόλος',
                'verbose_name_plural': 'Ρόλοι',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department', verbose_name='Τμήμα'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.role', verbose_name='Ρόλοι'),
        ),
    ]
