# Generated by Django 5.2.3 on 2025-06-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers_alter_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_category',
            field=models.CharField(blank=True, choices=[('ADMINISTRATIVE', 'Διοικητικοί'), ('EDUCATIONAL', 'Εκπαιδευτικοί'), ('SUBSTITUTE', 'Αναπληρωτές'), ('SDEU_SUPPORT', 'Κέντρο Στήριξης ΣΔΕΥ'), ('EDUCATION_DIRECTOR', 'Δ/ντές Εκπαίδευσης'), ('OTHER', 'Άλλο')], default='OTHER', max_length=20, verbose_name='Κατηγορία Χρήστη'),
        ),
    ]
