# Generated by Django 5.2.3 on 2025-06-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_user_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialties_full', models.CharField(max_length=200, unique=True, verbose_name='Πλήρης Ειδικότητα')),
                ('specialties_short', models.CharField(max_length=50, verbose_name='Σύντομη Ειδικότητα')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Ειδικότητα',
                'verbose_name_plural': 'Ειδικότητες',
                'ordering': ['specialties_short', 'specialties_full'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.specialty', verbose_name='Ειδικότητα'),
        ),
    ]
