# Generated by Django 5.2.3 on 2025-06-22 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_specialty_user_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Έγκρισης'),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Σημειώσεις Έγκρισης'),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Εγκρίθηκε από'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Εγγραφής'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('PENDING', 'Εκκρεμεί Έγκριση'), ('APPROVED', 'Εγκεκριμένος'), ('REJECTED', 'Απορριφθείς')], default='PENDING', max_length=20, verbose_name='Κατάσταση Εγγραφής'),
        ),
    ]
