# Generated by Django 5.2.3 on 2025-06-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_registration_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='headquarters',
            field=models.CharField(blank=True, choices=[('PATRA', 'Πάτρα'), ('MESSOLONGI', 'Μεσολόγγι'), ('PYRGOS', 'Πύργος'), ('KLEITORIA', 'Κλειτορία'), ('KRESTENA', 'Κρέστενα')], max_length=20, null=True, verbose_name='Έδρα'),
        ),
        migrations.AddField(
            model_name='department',
            name='prefecture',
            field=models.CharField(blank=True, choices=[('ACHAIA', 'Αχαΐας'), ('AITOLOAKARNANIA', 'Αιτωλοακαρνανίας'), ('ILIA', 'Ηλείας')], max_length=20, null=True, verbose_name='Νομός'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Κωδικός Τμήματος'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('DIRECTION', 'Διεύθυνση'), ('AUTONOMOUS_DIRECTION', 'Αυτοτελής Διεύθυνση'), ('DEPARTMENT', 'Τμήμα'), ('OFFICE', 'Γραφείο'), ('VIRTUAL_DEPARTMENT', 'Εικονικό Τμήμα')], max_length=30, verbose_name='Τύπος Τμήματος'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_category',
            field=models.CharField(blank=True, choices=[('ADMINISTRATIVE', 'Διοικητικοί'), ('EDUCATIONAL', 'Εκπαιδευτικοί'), ('SUBSTITUTE', 'Αναπληρωτές'), ('OTHER', 'Άλλο')], default='OTHER', max_length=20, verbose_name='Κατηγορία Χρήστη'),
        ),
    ]
