# Generated by Django 5.0 on 2025-06-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_department_headquarters_department_prefecture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Κωδικός Έδρας')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Έδρας')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Έδρα',
                'verbose_name_plural': 'Έδρες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Κωδικός Νομού')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Νομού')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Νομός',
                'verbose_name_plural': 'Νομοί',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='headquarters_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounts.headquarters', verbose_name='Έδρα'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='prefecture_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounts.prefecture', verbose_name='Νομός'),
            preserve_default=False,
        ),
    ]
