# Generated by Django 5.0 on 2025-06-29 08:26

from django.db import migrations


def link_headquarters_and_prefecture(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    Headquarters = apps.get_model('accounts', 'Headquarters')
    Prefecture = apps.get_model('accounts', 'Prefecture')

    # Update Department instances to link to Headquarters and Prefecture
    # This assumes that headquarters and prefecture fields in Department are still CharFields holding the code
    for dept in Department.objects.all():
        try:
            if dept.headquarters_char:
                hq = Headquarters.objects.get(code=dept.headquarters_char)
                dept.headquarters = hq
        except (Headquarters.DoesNotExist, AttributeError):
            pass
            
        try:
            if dept.prefecture_char:
                pref = Prefecture.objects.get(code=dept.prefecture_char)
                dept.prefecture = pref
        except (Prefecture.DoesNotExist, AttributeError):
            pass
            
        dept.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_data_migration_headquarters_prefecture'),
    ]

    operations = [
        migrations.RunPython(link_headquarters_and_prefecture),
    ]
