# Generated by Django 5.0 on 2025-06-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_data_migration_headquarters_prefecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='headquarters',
        ),
        migrations.RemoveField(
            model_name='department',
            name='prefecture',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='headquarters_temp',
            new_name='headquarters',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='prefecture_temp',
            new_name='prefecture',
        ),
    ]
