# Generated by Django 5.2.3 on 2025-06-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_data_migration_link_headquarters_prefecture'),
        ('accounts', '0012_final_field_replacement'),
    ]

    operations = [
    ]
