# Generated by Django 5.2.3 on 2025-06-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20250629_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarters',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Κωδικός Έδρας'),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Κωδικός Νομού'),
        ),
    ]
