# Generated by Django 5.2.3 on 2025-06-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_headquarters_code_alter_prefecture_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Κωδικός Τμήματος'),
        ),
    ]
