# Generated by Django 5.2.3 on 2025-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_department_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Άνδρας'), ('FEMALE', 'Γυναίκα'), ('OTHER', 'Άλλο')], max_length=10, verbose_name='Φύλο'),
        ),
    ]
