# Generated by Django 5.2.3 on 2025-07-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.TextField(blank=True, help_text='Υπηρεσίες που θα γίνει κοινοποίηση η απόφαση της άδειας', verbose_name='Κοινοποίηση Απόφασης'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.TextField(blank=True, help_text='Ιδιότητα του χρήστη', verbose_name='Περιγραφή Χρήστη'),
        ),
    ]
