# Generated by Django 5.2.3 on 2025-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_create_department_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Εναλλακτικό Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Πατρώνυμο'),
        ),
        migrations.AddField(
            model_name='user',
            name='orario',
            field=models.IntegerField(blank=True, help_text='Ώρες εργασίας', null=True, verbose_name='Ωράριο'),
        ),
    ]
