# Generated by Django 5.2.3 on 2025-07-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_personal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_leave_entitlement',
            field=models.IntegerField(default=25, help_text='Οι ημέρες κανονικής άδειας που δικαιούται κάθε χρόνο', verbose_name='Δικαιούμενες Ημέρες Κανονικής Άδειας'),
        ),
        migrations.AddField(
            model_name='user',
            name='carryover_leave_days',
            field=models.IntegerField(default=0, help_text='Μη εξαντλημένες κανονικές άδειες από το προηγούμενο έτος', verbose_name='Υπόλοιπο Κανονικών Αδειών Προηγούμενου Έτους'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_year_leave_balance',
            field=models.IntegerField(default=0, help_text='Διαθέσιμες κανονικές άδειες για το τρέχον έτος', verbose_name='Υπόλοιπο Κανονικών Αδειών Τρέχοντος Έτους'),
        ),
        migrations.AddField(
            model_name='user',
            name='sick_leave_with_declaration',
            field=models.IntegerField(default=2, help_text='Διαθέσιμες αναρρωτικές άδειες με υπεύθυνη δήλωση', verbose_name='Αναρρωτικές Άδειες με Υπεύθυνη Δήλωση'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_sick_leave_last_5_years',
            field=models.IntegerField(blank=True, default=0, help_text='Συνολικές αναρρωτικές άδειες των τελευταίων 5 ετών', null=True, verbose_name='Σύνολο Αναρρωτικών Αδειών Τελευταίας Πενταετίας'),
        ),
    ]
