# Generated by Django 5.2.3 on 2025-07-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_leave_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leave_balance',
            field=models.IntegerField(default=0, help_text='Συνολικό υπόλοιπο κανονικών αδειών (προηγούμενο + τρέχον έτος)', verbose_name='Υπόλοιπο Κανονικών Αδειών'),
        ),
    ]
