# Generated by Django 5.2.3 on 2026-02-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_add_leave_balance_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="accounts.department",
                verbose_name="Προϊστάμενος Τμήματος",
            ),
        ),
    ]
