# Generated by Django 5.2.3 on 2026-05-12 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_department_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Τύπου')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Τύπος Υπαλλήλου',
                'verbose_name_plural': 'Τύποι Υπαλλήλων',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Αλλαγής')),
                ('field_name', models.CharField(help_text='Ποιο πεδίο άλλαξε (specialty, employee_type, department, κλπ)', max_length=100, verbose_name='Πεδίο')),
                ('old_value', models.CharField(blank=True, max_length=200, verbose_name='Προηγούμενη Τιμή')),
                ('new_value', models.CharField(blank=True, max_length=200, verbose_name='Νέα Τιμή')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_changes', to=settings.AUTH_USER_MODEL, verbose_name='Αλλαγή από')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Ιστορικό Αλλαγής Υπαλλήλου',
                'verbose_name_plural': 'Ιστορικό Αλλαγών Υπαλλήλων',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='GDPRConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_text', models.TextField(verbose_name='Κείμενο Συναίνεσης')),
                ('consented_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Συναίνεσης')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Διεύθυνση')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version του κειμένου GDPR που αποδέχτηκε', verbose_name='Έκδοση Κειμένου')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_consents', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Συναίνεση GDPR',
                'verbose_name_plural': 'Συναινέσεις GDPR',
                'ordering': ['-consented_at'],
            },
        ),
    ]
