# Generated by Django 5.2.3 on 2026-05-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_employeetype_employeehistory_gdprconsent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notification',
            new_name='notification_recipients',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_description',
        ),
        migrations.AddField(
            model_name='department',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='True για ΣΔΕΥ - κληρονομούν προϊστάμενο από το γονικό ΚΕΔΑΣΥ', verbose_name='Εικονικό Τμήμα'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_own_leave',
            field=models.BooleanField(default=False, help_text='Αν είναι False, δεν μπορεί να εγκρίνει τη δική του αίτηση', verbose_name='Έγκριση Δικής Του Άδειας'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.employeetype', verbose_name='Τύπος Υπαλλήλου'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Προσωπικό Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, verbose_name='Τηλέφωνο 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_description',
            field=models.TextField(blank=True, help_text='Ιδιότητα του χρήστη', verbose_name='Περιγραφή Ρόλου'),
        ),
        migrations.AddField(
            model_name='user',
            name='sick_days_current_year',
            field=models.IntegerField(default=0, help_text='Σύνολο αναρρωτικών ημερών τρέχοντος έτους (για alert Υγειονομικής)', verbose_name='Αναρρωτικές Τρέχοντος Έτους'),
        ),
    ]
