# Generated by Django 5.2.3 on 2026-05-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_rename_notification_user_notification_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_request_leave',
            field=models.BooleanField(default=True, help_text='Αν είναι False, ο χρήστης δεν μπορεί να κάνει αίτηση άδειας (π.χ. SDEY managers, Περιφ. Δ/ντής)', verbose_name='Δικαίωμα Αίτησης Άδειας'),
        ),
    ]
