# Generated by Django 5.2.3 on 2026-05-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_can_request_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_regular_leave_balance',
            field=models.IntegerField(default=0, help_text='Denormalized cache του τελευταίου balance_after από το ledger', verbose_name='Τρέχον Υπόλοιπο Κανονικών (Ledger)'),
        ),
    ]
