# Generated by Django 5.2.3 on 2026-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_regular_leave_balance_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='has_atypical_leaves',
            field=models.BooleanField(default=False, help_text='Τα τμήματα που χειρίζονται άτυπες άδειες (π.χ. εκπαιδευτικοί)', verbose_name='Άτυπες Άδειες'),
        ),
    ]
