# Generated by Django 5.2.3 on 2026-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_department_has_atypical_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_accusative',
            field=models.CharField(blank=True, help_text='Αυτόματα δημιουργείται από το Όνομα και Επίθετο, π.χ. "Γεώργιο Νικολόπουλο"', max_length=150, verbose_name='Ονοματεπώνυμο (Αιτιατική)'),
        ),
    ]
