# Generated by Django 5.2.3 on 2026-06-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_name_accusative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_approve_own_leave',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone2',
        ),
    ]
