# Generated by Django 5.2.3 on 2026-06-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_user_can_approve_own_leave_remove_user_email2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdprconsent',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeHistory',
        ),
        migrations.DeleteModel(
            name='GDPRConsent',
        ),
    ]
