# Generated by Django 5.2.3 on 2026-06-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_employee_history_and_gdpr_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_virtual',
        ),
    ]
