# Generated by Django 5.2.3 on 2026-06-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_normalize_role_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_regular_leave_balance',
            field=models.IntegerField(default=0, help_text='Cache του τελευταίου balance_after από το ledger', verbose_name='Υπόλοιπο Κανονικών Αδειών'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.employeetype', verbose_name='Κατηγορία Υπαλλήλου'),
        ),
    ]
