# Generated by Django 5.2.3 on 2026-06-23 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_pending_registration_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationApprovalEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Χρησιμοποιήστε placeholders όπως {full_name}', max_length=255, verbose_name='Θέμα Email')),
                ('body', models.TextField(help_text='Χρησιμοποιήστε placeholders όπως {full_name}, {login_psd_url}', verbose_name='Κείμενο Email')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_email_template_updates', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
            ],
            options={
                'verbose_name': 'Πρότυπο Email Ενεργοποίησης',
                'verbose_name_plural': 'Πρότυπο Email Ενεργοποίησης',
            },
        ),
    ]
