# Generated by Django 5.2.3 on 2026-07-23 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_remove_alt_login_from_approval_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gdpr_consent_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Πότε αποδέχτηκε την τρέχουσα συγκατάθεση επεξεργασίας δεδομένων', null=True, verbose_name='Ημερομηνία Συγκατάθεσης GDPR'),
        ),
        migrations.AddField(
            model_name='user',
            name='gdpr_consent_version',
            field=models.PositiveIntegerField(default=0, help_text='Έκδοση κειμένου GDPR που έχει αποδεχτεί ο χρήστης', verbose_name='Έκδοση Συγκατάθεσης GDPR'),
        ),
        migrations.CreateModel(
            name='GDPRConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_text', models.TextField(verbose_name='Κείμενο Συγκατάθεσης')),
                ('consented_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Συγκατάθεσης')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Διεύθυνση')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User Agent')),
                ('version', models.PositiveIntegerField(default=1, help_text='Έκδοση του κειμένου GDPR που αποδέχτηκε', verbose_name='Έκδοση Κειμένου')),
                ('do_not_show_again', models.BooleanField(default=True, help_text='Ο χρήστης επιβεβαίωσε ότι η συγκατάθεση καταγράφηκε και δεν θα εμφανιστεί ξανά', verbose_name='Να μην εμφανιστεί ξανά')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_consents', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Συγκατάθεση GDPR',
                'verbose_name_plural': 'Συγκαταθέσεις GDPR',
                'ordering': ['-consented_at'],
            },
        ),
    ]
