# Generated by Django 5.2.3 on 2026-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_gdpr_consent_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetype',
            name='is_permanent_dy',
            field=models.BooleanField(default=False, help_text='Αν ο τύπος αφορά μόνιμους δημόσιους υπαλλήλους (ΔΥ)', verbose_name='Μόνιμοι ΔΥ'),
        ),
    ]
