# Generated by Django 5.2.3 on 2026-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_employee_type_is_permanent_dy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='substitute_leave_status',
            field=models.CharField(choices=[('ACTIVE', 'Ενεργή σύμβαση'), ('PENDING_CONTRACT', 'Αναμονή νέας σύμβασης'), ('ENDED_NO_REHIRE', 'Έληξε χωρίς επαναπρόσληψη')], default='ACTIVE', help_text='Ισχύει για αναπληρωτές: ACTIVE επιτρέπει αιτήσεις, PENDING_CONTRACT τις μπλοκάρει', max_length=20, verbose_name='Κατάσταση Σύμβασης Αναπληρωτή'),
        ),
        migrations.AddField(
            model_name='user',
            name='substitute_reappearance_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Τελευταία ειδοποίηση επανεμφάνισης'),
        ),
    ]
