# Fail2Ban custom email με ελληνική περιγραφή (καλεί εξωτερικό script)
[Definition]
actionstart =
actionstop =
actioncheck =
actionban = /usr/local/bin/fail2ban-pdede-mail.sh <name> <ip> <failures> <dest> <sender> "<sendername>"
actionunban =

[Init]
name = default
dest = apettas@gmail.com
sender = andpettas@sch.gr
sendername = Adeies Fail2Ban
