# Generated by Django 5.0.1 on 2025-06-21 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Τύπου Άδειας')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Κωδικός')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('max_days_per_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Μέγιστες Ημέρες/Έτος')),
                ('requires_documents', models.BooleanField(default=False, verbose_name='Απαιτεί Δικαιολογητικά')),
                ('logic_handler', models.CharField(default='default', max_length=50, verbose_name='Χειριστής Λογικής')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Τύπος Άδειας',
                'verbose_name_plural': 'Τύποι Αδειών',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='Συνολικές Ημέρες')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή/Αιτιολογία')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Υποβλήθηκε'), ('APPROVED_MANAGER', 'Εγκρίθηκε από Προϊστάμενο'), ('FOR_PROTOCOL_PDEDE', 'Για Πρωτόκολλο ΠΔΕΔΕ'), ('UNDER_PROCESSING', 'Προς Επεξεργασία'), ('APPROVED', 'Εγκρίθηκε'), ('COMPLETED', 'Ολοκληρώθηκε'), ('REJECTED_MANAGER', 'Απορρίφθηκε από Προϊστάμενο'), ('REJECTED_OPERATOR', 'Απορρίφθηκε από Χειριστή')], default='SUBMITTED', max_length=30, verbose_name='Κατάσταση')),
                ('protocol_number', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Πρωτοκόλλου')),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Έγκρισης Προϊσταμένου')),
                ('manager_comments', models.TextField(blank=True, verbose_name='Σχόλια Προϊσταμένου')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Επεξεργασίας')),
                ('processing_comments', models.TextField(blank=True, verbose_name='Σχόλια Επεξεργασίας')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Απόρριψης')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Αιτιολογία Απόρριψης')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Εγκρίθηκε από Προϊστάμενο')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Επεξεργάστηκε από')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to=settings.AUTH_USER_MODEL, verbose_name='Απορρίφθηκε από')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype', verbose_name='Τύπος Άδειας')),
            ],
            options={
                'verbose_name': 'Αίτηση Άδειας',
                'verbose_name_plural': 'Αιτήσεις Αδειών',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='leave_documents/%Y/%m/', verbose_name='Αρχείο')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Περιγραφή')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Μεταφόρτωσης')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leaves.leaverequest', verbose_name='Αίτηση Άδειας')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Μεταφορτώθηκε από')),
            ],
            options={
                'verbose_name': 'Δικαιολογητικό Άδειας',
                'verbose_name_plural': 'Δικαιολογητικά Αδειών',
            },
        ),
    ]
