# Generated by Django 5.0.1 on 2025-06-21 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Τμήματος')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Κωδικός Τμήματος')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Τμήμα',
                'verbose_name_plural': 'Τμήματα',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_leave', 'Μπορεί να εγκρίνει άδειες'), ('can_process_leave', 'Μπορεί να επεξεργαστεί άδειες')], 'verbose_name': 'Αίτηση Άδειας', 'verbose_name_plural': 'Αιτήσεις Αδειών'},
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='logic_handler',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='max_days_per_year',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='requires_documents',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ολοκλήρωσης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Υποβολής'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Μέγιστες Ημέρες'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='Απαιτεί Έγκριση'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Εγκρίθηκε από Προϊστάμενο'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Επεξεργάστηκε από'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='protocol_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Πρωτοκόλλου'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Απορρίφθηκε από'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Λόγος Απόρριψης'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Προσχέδιο'), ('SUBMITTED', 'Υποβλήθηκε'), ('APPROVED_MANAGER', 'Εγκρίθηκε από Προϊστάμενο'), ('REJECTED_MANAGER', 'Απορρίφθηκε από Προϊστάμενο'), ('FOR_PROTOCOL_PDEDE', 'Για Πρωτόκολλο ΠΔΕΔΕ'), ('UNDER_PROCESSING', 'Προς Επεξεργασία'), ('COMPLETED', 'Ολοκληρώθηκε'), ('REJECTED_OPERATOR', 'Απορρίφθηκε από Χειριστή')], default='DRAFT', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Όνομα Τύπου'),
        ),
        migrations.CreateModel(
            name='SecureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Αρχικό Όνομα Αρχείου')),
                ('file_path', models.CharField(max_length=500, verbose_name='Διαδρομή Αρχείου')),
                ('file_size', models.PositiveIntegerField(verbose_name='Μέγεθος Αρχείου (bytes)')),
                ('content_type', models.CharField(max_length=100, verbose_name='Τύπος Περιεχομένου')),
                ('encryption_key', models.CharField(max_length=64, verbose_name='Κλειδί Κρυπτογράφησης')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Αποστολής')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='leaves.leaverequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ασφαλές Αρχείο',
                'verbose_name_plural': 'Ασφαλή Αρχεία',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='LeaveRequestDocument',
        ),
    ]
