# Generated by Django 5.2.3 on 2025-06-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_department_alter_leaverequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.CreateModel(
            name='LeavePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='leaves.leaverequest', verbose_name='Αίτηση Άδειας')),
            ],
            options={
                'verbose_name': 'Διάστημα Άδειας',
                'verbose_name_plural': 'Διαστήματα Αδειών',
                'ordering': ['start_date'],
            },
        ),
    ]
