# Generated by Django (manually created for adding description field to SecureFile)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_remove_leaverequest_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Περιγραφή Αρχείου'),
        ),
    ]
