# Generated by Django 5.2.3 on 2025-06-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_add_securefile_description'),
        ('leaves', '0004_leavetype_decision_text_leavetype_folder_and_more'),
    ]

    operations = [
    ]
