# Generated by Django 5.2.3 on 2025-07-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0005_merge_20250629_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="protocol_pdf_encryption_key",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="Κλειδί Κρυπτογράφησης Πρωτοκόλλου",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="protocol_pdf_path",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Διαδρομή Πρωτοκολλημένου PDF"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="protocol_pdf_size",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Μέγεθος Πρωτοκολλημένου PDF"
            ),
        ),
    ]
