# Generated by Django 5.2.3 on 2025-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0006_add_protocol_pdf_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info_short",
                    models.CharField(
                        max_length=100, verbose_name="Σύντομες Πληροφορίες"
                    ),
                ),
                ("info", models.TextField(verbose_name="Πλήρεις Πληροφορίες")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία Δημιουργίας"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ημερομηνία Ενημέρωσης"
                    ),
                ),
            ],
            options={
                "verbose_name": "Πληροφορίες",
                "verbose_name_plural": "Πληροφορίες",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_short",
                    models.CharField(max_length=100, verbose_name="Σύντομο Λογότυπο"),
                ),
                ("logo", models.TextField(verbose_name="Πλήρες Λογότυπο")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία Δημιουργίας"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ημερομηνία Ενημέρωσης"
                    ),
                ),
            ],
            options={
                "verbose_name": "Λογότυπο",
                "verbose_name_plural": "Λογότυπα",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Signee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signee_short",
                    models.CharField(max_length=100, verbose_name="Σύντομη Περιγραφή"),
                ),
                (
                    "signee_name",
                    models.CharField(max_length=200, verbose_name="Ονοματεπώνυμο"),
                ),
                ("signee", models.TextField(verbose_name="Πλήρες Κείμενο Υπογραφής")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία Δημιουργίας"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ημερομηνία Ενημέρωσης"
                    ),
                ),
            ],
            options={
                "verbose_name": "Υπογράφων",
                "verbose_name_plural": "Υπογράφοντες",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ypopsin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ypopsin_short",
                    models.CharField(max_length=200, verbose_name="Σύντομη Περιγραφή"),
                ),
                ("ypopsin", models.TextField(verbose_name="Πλήρες Κείμενο Υπόψη")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ημερομηνία Δημιουργίας"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ημερομηνία Ενημέρωσης"
                    ),
                ),
            ],
            options={
                "verbose_name": "Έχοντας Υπόψη",
                "verbose_name_plural": "Έχοντας Υπόψη",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
    ]
