# Generated by Django 5.2.3 on 2025-07-05 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_populate_decision_content_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='decision_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Δημιουργίας Απόφασης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.info', verbose_name='Πληροφορίες Απόφασης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.logo', verbose_name='Λογότυπο Απόφασης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_pdf_encryption_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='Κλειδί Κρυπτογράφησης Απόφασης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_pdf_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Διαδρομή PDF Απόφασης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_pdf_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Μέγεθος PDF Απόφασης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_signee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.signee', verbose_name='Υπογράφων Απόφασης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='decision_ypopsin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.ypopsin', verbose_name='Έχοντας Υπόψη Απόφασης'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='final_decision_text',
            field=models.TextField(blank=True, verbose_name='Τελικό Κείμενο Απόφασης'),
        ),
    ]
