# Generated by Django 4.2.10 on 2025-07-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0012_add_final_decision_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='decision_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]