# Generated by Django 4.2.10 on 2025-07-06 01:35
# This migration is a no-op since the field already exists in the database

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0012_add_final_decision_text'),
    ]

    def do_nothing(apps, schema_editor):
        """No-op function since field already exists"""
        pass

    operations = [
        migrations.RunPython(do_nothing, do_nothing),
    ]