# Generated by Django 5.2.3 on 2025-07-11 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0013_add_decision_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='exact_copy_pdf_encryption_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='Κλειδί Κρυπτογράφησης Ακριβούς Αντιγράφου'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='exact_copy_pdf_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Διαδρομή Ακριβούς Αντιγράφου'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='exact_copy_pdf_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Μέγεθος Ακριβούς Αντιγράφου'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='exact_copy_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αποστολής Ακριβούς Αντιγράφου'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='exact_copy_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_exact_copies', to=settings.AUTH_USER_MODEL, verbose_name='Ανέβασε το Ακριβές Αντίγραφο'),
        ),
    ]
