# Generated by Django 4.2 on 2025-01-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0014_add_exact_copy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='protocol_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Πρωτοκόλλησης'),
        ),
    ]