# Generated by Django 5.2.3 on 2025-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0015_add_protocol_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='Απαιτεί Έγκριση από Προϊστάμενο'),
        ),
    ]
