# Generated by Django 4.2.7 on 2024-12-10 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0017_add_kedasy_kepea_protocol_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Προσχέδιο'), ('SUBMITTED', 'Υποβλήθηκε'), ('APPROVED_MANAGER', 'Εγκρίθηκε από Προϊστάμενο'), ('REJECTED_MANAGER', 'Απορρίφθηκε από Προϊστάμενο'), ('PENDING_KEDASY_KEPEA_PROTOCOL', 'Εκκρεμεί Πρωτόκολλο ΚΕΔΑΣΥ/ΚΕΠΕΑ'), ('FOR_PROTOCOL_PDEDE', 'Για Πρωτόκολλο ΠΔΕΔΕ'), ('PENDING_DOCUMENTS', 'Σε Αναμονή Δικαιολογητικών'), ('UNDER_PROCESSING', 'Προς Επεξεργασία'), ('COMPLETED', 'Ολοκληρώθηκε'), ('REJECTED_OPERATOR', 'Απορρίφθηκε από Χειριστή'), ('WITHDRAWN_BY_REQUESTER', 'Ανάκληση Αίτησης από Αιτούντα')], default='DRAFT', max_length=40, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='documents_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Προθεσμία Κατάθεσης Δικαιολογητικών'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='documents_notes',
            field=models.TextField(blank=True, verbose_name='Σημειώσεις Δικαιολογητικών'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='documents_provided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Παροχής Δικαιολογητικών'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='documents_provided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_documents', to=settings.AUTH_USER_MODEL, verbose_name='Παρείχε Δικαιολογητικά'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='documents_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αιτήματος Δικαιολογητικών'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='documents_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_documents', to=settings.AUTH_USER_MODEL, verbose_name='Ζήτησε Δικαιολογητικά'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='required_documents',
            field=models.TextField(blank=True, help_text='Περιγραφή των δικαιολογητικών που χρειάζονται', verbose_name='Απαιτούμενα Δικαιολογητικά'),
        ),
    ]