# Generated by Django 5.2.3 on 2026-05-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0018_add_documents_workflow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
