# Generated by Django 5.2.3 on 2026-05-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0019_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='counts_against_balance',
            field=models.BooleanField(default=True, help_text='Αν είναι ενεργό, οι ημέρες αυτής της άδειας αφαιρούνται από το υπόλοιπο του χρήστη', verbose_name='Μετράει σε Υπόλοιπο Αδειών'),
        ),
    ]
