# Generated by Django 5.2.3 on 2026-05-12 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0020_leavetype_counts_against_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('VIEW', 'Προβολή'), ('DOWNLOAD', 'Λήψη')], max_length=20, verbose_name='Τύπος Πρόσβασης')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία/Ώρα')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Διεύθυνση')),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Πρόσβαση από')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='leaves.leaverequest', verbose_name='Αίτηση Άδειας')),
            ],
            options={
                'verbose_name': 'Log Πρόσβασης Άδειας',
                'verbose_name_plural': 'Logs Πρόσβασης Αδειών',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeaveActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Ενέργεια')),
                ('previous_status', models.CharField(blank=True, max_length=50, verbose_name='Προηγούμενη Κατάσταση')),
                ('new_status', models.CharField(blank=True, max_length=50, verbose_name='Νέα Κατάσταση')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία/Ώρα')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Διεύθυνση')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='leaves.leaverequest', verbose_name='Αίτηση Άδειας')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Log Ενέργειας Άδειας',
                'verbose_name_plural': 'Logs Ενεργειών Αδειών',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Letterhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(help_text='Υπουργείο, Διεύθυνση, Τμήμα - εμφανίζεται σε όλα τα PDF', verbose_name='Κείμενο Επικεφαλίδας')),
                ('address', models.CharField(default='Ακτής Δυμαίων 25α, Πάτρα', max_length=200, verbose_name='Διεύθυνση')),
                ('postal_code', models.CharField(default='26222', max_length=10, verbose_name='Ταχ. Κώδικας')),
                ('contact_info_template', models.CharField(blank=True, help_text='Πρότυπο για πληροφορίες επικοινωνίας', max_length=200, verbose_name='Πρότυπο Πληροφοριών')),
                ('coat_of_arms', models.ImageField(blank=True, help_text='Coat_of_arms_of_Greece.jpg', null=True, upload_to='letterhead/', verbose_name='Έμβλημα')),
                ('is_active', models.BooleanField(default=True, help_text='Μόνο μία επικεφαλίδα μπορεί να είναι ενεργή', verbose_name='Ενεργή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Επικεφαλίδα Εγγράφου',
                'verbose_name_plural': 'Επικεφαλίδες Εγγράφων',
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Όνομα Αργίας')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('is_movable', models.BooleanField(default=False, help_text='True για κινητές εορτές (π.χ. Πάσχα), False για σταθερές', verbose_name='Κινητή Εορτή')),
                ('year', models.PositiveIntegerField(verbose_name='Έτος')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Δημόσια Αργία',
                'verbose_name_plural': 'Δημόσιες Αργίες',
                'ordering': ['date'],
                'unique_together': {('date', 'name')},
            },
        ),
    ]
