# Generated by Django 5.2.3 on 2026-05-12 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0021_leaveaccesslog_leaveactionlog_letterhead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ώρα Κλειδώματος'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='locking_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Κλειδωμένο από Χειριστή'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='parent_leave',
            field=models.ForeignKey(blank=True, help_text='Για ανάκληση/μερική ανάκληση - συνδέει με την αρχική αίτηση', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requests', to='leaves.leaverequest', verbose_name='Γονική Αίτηση'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='revoked_days',
            field=models.IntegerField(default=0, help_text='Ημέρες που ανακλήθηκαν από την αρχική αίτηση', verbose_name='Ανακληθείσες Ημέρες'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='id_adeias',
            field=models.CharField(blank=True, max_length=50, verbose_name='Κωδικός Άδειας (ID Αδείας)'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_simple',
            field=models.BooleanField(default=False, help_text='Για εορταστικές/προφορικές/επιμορφωτικές άδειες', verbose_name='Απλή Άδεια'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='name_simple',
            field=models.CharField(blank=True, max_length=100, verbose_name='Απλό Όνομα'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='thematic_folder',
            field=models.CharField(blank=True, max_length=255, verbose_name='Θεματικός Φάκελος'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Προσχέδιο'), ('SUBMITTED', 'ΚΑΤΑΧΩΡΗΘΗΚΕ'), ('APPROVED_MANAGER', 'ΕΓΚΡΙΣΗ ΑΠΟ ΠΡΟΪΣΤΑΜΕΝΟ'), ('REJECTED_MANAGER', 'ΜΗ ΕΓΚΡΙΣΗ ΑΠΟ ΠΡΟΪΣΤΑΜΕΝΟ'), ('PENDING_KEDASY_KEPEA_PROTOCOL', 'ΓΙΑ ΠΡΩΤΟΚΟΛΛΟ ΚΕΔΑΣΥ'), ('FOR_PROTOCOL_PDEDE', 'ΓΙΑ ΠΡΩΤΟΚΟΛΛΟ ΠΔΕΔΕ'), ('PENDING_DOCUMENTS', 'ΣΕ ΑΝΑΜΟΝΗ ΔΙΚ/ΚΩΝ'), ('UNDER_PROCESSING', 'ΠΡΟΣ ΕΠΕΞΕΡΓΑΣΙΑ'), ('COMPLETED', 'ΟΛΟΚΛΗΡΩΜΕΝΗ'), ('REJECTED_OPERATOR', 'ΑΠΟΡΡΙΨΗ ΑΠΟ ΤΜΗΜΑ ΑΔΕΙΩΝ'), ('WITHDRAWN_BY_REQUESTER', 'ΑΝΑΚΛΗΣΗ ΑΙΤΗΣΗΣ ΑΠΟ ΑΙΤΟΥΝΤΑ'), ('WITHDRAWN_COMPLETED', 'ΑΝΑΚΛΗΣΗ ΟΛΟΚΛΗΡΩΜΕΝΗΣ ΑΔΕΙΑΣ'), ('HEALTH_COMMITTEE', 'ΥΓΕΙΟΝΟΜΙΚΗ ΕΠΙΤΡΟΠΗ'), ('DELETED_BY_HANDLER', 'ΔΙΑΓΡΑΦΗ ΑΠΟ ΧΕΙΡΙΣΤΗ')], default='DRAFT', max_length=40, verbose_name='Κατάσταση'),
        ),
    ]
