# Generated by Django 5.2.3 on 2026-05-15 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0022_leaverequest_locked_at_leaverequest_locking_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='affects_regular_leave_balance',
            field=models.BooleanField(default=True, help_text='Αν είναι ενεργό, η ολοκλήρωση αυτής της άδειας δημιουργεί εγγραφή στο ιστορικό υπολοίπου', verbose_name='Επηρεάζει Υπόλοιπο Κανονικών'),
        ),
        migrations.CreateModel(
            name='RegularLeaveBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('INITIAL_BALANCE', 'Αρχικό Υπόλοιπο'), ('LEAVE_GRANTED', 'Χορήγηση Κανονικής Άδειας'), ('LEAVE_REVOKED', 'Ανάκληση Άδειας'), ('MANUAL_ADJUSTMENT', 'Διοικητική Διόρθωση'), ('CARRYOVER_IMPORT', 'Μεταφορά Υπολοίπου'), ('PREVIOUS_YEAR_CORRECTION', 'Διόρθωση Προηγούμενου Έτους'), ('ADMIN_CORRECTION', 'Διόρθωση Χειριστή')], max_length=30, verbose_name='Τύπος Κίνησης')),
                ('entry_date', models.DateField(verbose_name='Ημερομηνία Κίνησης')),
                ('description', models.CharField(max_length=200, verbose_name='Περιγραφή')),
                ('days_delta', models.IntegerField(blank=True, help_text='Θετικό για επιστροφή, αρνητικό για αφαίρεση', null=True, verbose_name='Μεταβολή Ημερών')),
                ('balance_after', models.IntegerField(help_text='Υπόλοιπο μετά την κίνηση (source of truth)', verbose_name='Υπόλοιπο Μετά')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('is_locked', models.BooleanField(default=True, help_text='Append-only — οι διορθώσεις είναι νέες εγγραφές', verbose_name='Κλειδωμένο')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_balance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_leave_balance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_entries', to='leaves.leaverequest', verbose_name='Αίτηση Άδειας')),
            ],
            options={
                'verbose_name': 'Εγγραφή Υπολοίπου Κανονικών Αδειών',
                'verbose_name_plural': 'Ιστορικό Υπολοίπου Κανονικών Αδειών',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
