# Generated by Django 5.2.3 on 2026-05-15 11:24

from django.db import migrations
from django.utils import timezone


def create_initial_balance_entries(apps, schema_editor):
    """
    Create INITIAL_BALANCE entries for all active users based on their
    current_year_leave_balance. This seeds the ledger with initial data.
    """
    User = apps.get_model('accounts', 'User')
    RegularLeaveBalanceEntry = apps.get_model('leaves', 'RegularLeaveBalanceEntry')
    
    active_users = User.objects.filter(is_active=True)
    created_count = 0
    
    for user in active_users:
        # Use current_year_leave_balance as the starting balance
        # If it's 0, skip (user has no balance to seed)
        balance = user.current_year_leave_balance
        
        # If current_year_leave_balance is 0 but leave_balance has a value, use that
        if balance == 0 and user.leave_balance > 0:
            balance = user.leave_balance
        
        if balance > 0 or balance == 0:  # Create entry even for 0 balance
            RegularLeaveBalanceEntry.objects.create(
                employee=user,
                entry_type='INITIAL_BALANCE',
                entry_date=timezone.now().date(),
                description='Αρχικό υπόλοιπο — Εισαγωγή από υπάρχον σύστημα',
                balance_after=balance,
                days_delta=None,
                notes='Αυτόματη εισαγωγή κατά την ενεργοποίηση του ledger',
                created_by=None  # System-created
            )
            created_count += 1
    
    print(f'Created {created_count} initial balance entries')


def reverse_migration(apps, schema_editor):
    """Remove all INITIAL_BALANCE entries created by this migration."""
    RegularLeaveBalanceEntry = apps.get_model('leaves', 'RegularLeaveBalanceEntry')
    RegularLeaveBalanceEntry.objects.filter(
        entry_type='INITIAL_BALANCE',
        notes='Αυτόματη εισαγωγή κατά την ενεργοποίηση του ledger'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0023_add_regular_leave_balance_ledger'),
    ]

    operations = [
        migrations.RunPython(create_initial_balance_entries, reverse_migration),
    ]
