# Generated by Django 5.2.3 on 2026-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0024_create_initial_balance_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Πρόχειρη αίτηση'), ('SUBMITTED', 'Υποβληθείσα αίτηση'), ('PENDING_PROTOCOL', 'Για πρωτόκολλο ΠΔΕΔΕ'), ('IN_REVIEW', 'Σε επεξεργασία από τμήμα αδειών'), ('WAITING_FOR_DOCUMENTS', 'Σε αναμονή δικαιολογητικών'), ('DECISION_PREPARATION', 'Ετοιμασία απόφασης'), ('PENDING_SIGNATURES', 'ΣΗΔΕ - προς υπογραφές'), ('COMPLETED', 'Ολοκληρώθηκε'), ('SUPERVISOR_REJECTED', 'Αρνητική έγκριση προϊσταμένου'), ('REJECTED_BY_LEAVES_DEPT', 'Απόρριψη από τμήμα αδειών'), ('CANCELLED_BY_APPLICANT', 'Ανάκληση από αιτούντα')], default='DRAFT', max_length=40, verbose_name='Κατάσταση'),
        ),
    ]
