# Generated by Django 5.2.3 on 2026-05-15 11:43

from django.db import migrations


def migrate_statuses(apps, schema_editor):
    """
    Map old STATUS_CHOICES to new ones:
    - APPROVED_MANAGER → PENDING_PROTOCOL
    - REJECTED_MANAGER → SUPERVISOR_REJECTED
    - PENDING_KEDASY_KEPEA_PROTOCOL → PENDING_PROTOCOL
    - FOR_PROTOCOL_PDEDE → PENDING_PROTOCOL
    - PENDING_DOCUMENTS → WAITING_FOR_DOCUMENTS
    - UNDER_PROCESSING → IN_REVIEW
    - REJECTED_OPERATOR → REJECTED_BY_LEAVES_DEPT
    - WITHDRAWN_BY_REQUESTER → CANCELLED_BY_APPLICANT
    - WITHDRAWN_COMPLETED → CANCELLED_BY_APPLICANT
    - HEALTH_COMMITTEE → IN_REVIEW
    - DELETED_BY_HANDLER → REJECTED_BY_LEAVES_DEPT
    """
    LeaveRequest = apps.get_model('leaves', 'LeaveRequest')

    mapping = {
        'APPROVED_MANAGER': 'PENDING_PROTOCOL',
        'REJECTED_MANAGER': 'SUPERVISOR_REJECTED',
        'PENDING_KEDASY_KEPEA_PROTOCOL': 'PENDING_PROTOCOL',
        'FOR_PROTOCOL_PDEDE': 'PENDING_PROTOCOL',
        'PENDING_DOCUMENTS': 'WAITING_FOR_DOCUMENTS',
        'UNDER_PROCESSING': 'IN_REVIEW',
        'REJECTED_OPERATOR': 'REJECTED_BY_LEAVES_DEPT',
        'WITHDRAWN_BY_REQUESTER': 'CANCELLED_BY_APPLICANT',
        'WITHDRAWN_COMPLETED': 'CANCELLED_BY_APPLICANT',
        'HEALTH_COMMITTEE': 'IN_REVIEW',
        'DELETED_BY_HANDLER': 'REJECTED_BY_LEAVES_DEPT',
    }

    for old_status, new_status in mapping.items():
        count = LeaveRequest.objects.filter(status=old_status).update(status=new_status)
        if count > 0:
            print(f'Mapped {count} records: {old_status} → {new_status}')


def reverse_migration(apps, schema_editor):
    """Reverse is not safe — old states are not one-to-one with new states."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0025_fsm_redesign_status_choices'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_migration),
    ]
