# Generated by Django 5.2.3 on 2026-05-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0026_fsm_redesign_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='STANDARD, KEDASY, SDEY', max_length=30, unique=True, verbose_name='Κωδικός')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('requires_supervisor_approval', models.BooleanField(default=True, verbose_name='Απαιτεί Έγκριση Προϊσταμένου')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
            ],
            options={
                'verbose_name': 'Workflow Variant',
                'verbose_name_plural': 'Workflow Variants',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='leavetype',
            name='workflow_variant',
            field=models.CharField(default='STANDARD', help_text='STANDARD, KEDASY, SDEY - καθορίζει το approval path και τα rules', max_length=30, verbose_name='Workflow Variant'),
        ),
        migrations.CreateModel(
            name='RequiredAttachmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=200, verbose_name='Όνομα Συνημμένου')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_required', models.BooleanField(default=True, verbose_name='Υποχρεωτικό')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_rules', to='leaves.leavetype', verbose_name='Τύπος Άδειας')),
                ('workflow_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_rules', to='leaves.workflowvariant', verbose_name='Workflow Variant')),
            ],
            options={
                'verbose_name': 'Κανόνας Συνημμένου',
                'verbose_name_plural': 'Κανόνες Συνημμένων',
                'ordering': ['workflow_variant', 'leave_type', 'attachment_name'],
            },
        ),
        migrations.CreateModel(
            name='DecisionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='decision_templates/', verbose_name='Αρχείο Template')),
                ('header_text', models.TextField(blank=True, help_text='Αντικαθιστά το default header', verbose_name='Κείμενο Επικεφαλίδας')),
                ('subject_text', models.TextField(blank=True, help_text='Αντικαθιστά το default subject', verbose_name='Κείμενο Θέματος')),
                ('decision_body_template', models.TextField(blank=True, help_text='Jinja2/Django template body', verbose_name='Πρότυπο Σώματος Απόφασης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_templates', to='leaves.leavetype', verbose_name='Τύπος Άδειας')),
                ('workflow_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_templates', to='leaves.workflowvariant', verbose_name='Workflow Variant')),
            ],
            options={
                'verbose_name': 'Template Απόφασης',
                'verbose_name_plural': 'Templates Αποφάσεων',
                'ordering': ['workflow_variant', 'leave_type'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_type_code', models.CharField(blank=True, help_text='Αφήστε κενό για όλους τους τύπους', max_length=30, verbose_name='Τύπος Τμήματος')),
                ('approver_role', models.CharField(choices=[('DEPT_MANAGER', 'Προϊστάμενος Τμήματος'), ('KEDASY_HEAD', 'Προϊστάμενος ΚΕΔΑΣΥ'), ('LEAVE_HANDLER', 'Χειριστής Αδειών'), ('REGIONAL_DIRECTOR', 'Περιφερειακός Διευθυντής')], max_length=30, verbose_name='Ρόλος Εγκρίνοντα')),
                ('approval_order', models.PositiveIntegerField(default=1, help_text='1 = πρώτος εγκρίνων, 2 = δεύτερος, κλπ', verbose_name='Σειρά Έγκρισης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('workflow_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='leaves.workflowvariant', verbose_name='Workflow Variant')),
            ],
            options={
                'verbose_name': 'Κανόνας Έγκρισης',
                'verbose_name_plural': 'Κανόνες Έγκρισης',
                'ordering': ['workflow_variant', 'department_type_code', 'approval_order'],
            },
        ),
    ]
