# Generated by Django 5.2.3 on 2026-05-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0027_variant_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='code',
            field=models.CharField(blank=True, help_text='Προγραμματικός κωδικός (π.χ. ANNUAL, SICK, BLOOD)', max_length=50, unique=True, verbose_name='Κωδικός'),
        ),
    ]
