# Generated by Django 5.2.3 on 2026-05-16 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0028_add_leavetype_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='pdede_protocol_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdede_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Πρωτοκολλήθηκε από (ΠΔΕΔΕ)'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='pdede_protocol_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Πρωτοκόλλου ΠΔΕΔΕ'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='pdede_protocol_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Πρωτοκόλλου ΠΔΕΔΕ'),
        ),
    ]
