# Generated by Django 5.2.3 on 2026-05-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0029_add_pdede_protocol_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='pdede_protocol_details',
            field=models.TextField(blank=True, verbose_name='Στοιχεία Πρωτοκόλλου ΠΔΕΔΕ'),
        ),
    ]
