# Generated by Django 5.2.3 on 2026-05-18 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0030_add_pdede_protocol_details_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='return_notes',
            field=models.TextField(blank=True, verbose_name='Σημειώσεις Επιστροφής'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Επιστροφής'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Επιστράφηκε από'),
        ),
    ]
