# Generated by Django 5.2.3 on 2026-05-23 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0031_add_return_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regularleavebalanceentry',
            name='balance_before',
            field=models.IntegerField(default=0, help_text='Υπόλοιπο πριν από την κίνηση', verbose_name='Υπόλοιπο Πριν'),
        ),
        migrations.AddField(
            model_name='regularleavebalanceentry',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='Οριστικοποιημένες εγγραφές δεν τροποποιούνται', verbose_name='Οριστικοποιημένο'),
        ),
        migrations.AddField(
            model_name='regularleavebalanceentry',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Επαλήθευσης'),
        ),
        migrations.AddField(
            model_name='regularleavebalanceentry',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_balance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Επαληθεύτηκε από'),
        ),
    ]
