# Generated by Django 5.2.3 on 2026-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0032_regularleavebalanceentry_balance_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_sick_leave_yd',
            field=models.BooleanField(default=False, help_text='Αν είναι ενεργό, μετράει στο ετήσιο όριο αναρρωτικών με ΥΔ (2/έτος)', verbose_name='Αναρρωτική Άδεια με ΥΔ'),
        ),
    ]
