# Generated by Django 5.2.3 on 2026-05-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0033_leavetype_is_sick_leave_yd'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_sick_leave_total',
            field=models.BooleanField(default=False, help_text='Αν είναι ενεργό, οι ημέρες μετράνε στο σύνολο αναρρωτικών του έτους (για alert Υγειονομικής Επιτροπής)', verbose_name='Σύνολο Αναρρωτικών'),
        ),
    ]
