# Generated by Django 5.2.3 on 2026-05-24 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0034_leavetype_is_sick_leave_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Πρόχειρη αίτηση'), ('SUBMITTED', 'Υποβληθείσα αίτηση'), ('PENDING_PROTOCOL', 'Για πρωτόκολλο ΠΔΕΔΕ'), ('IN_REVIEW', 'Σε επεξεργασία από τμήμα αδειών'), ('WAITING_FOR_DOCUMENTS', 'Σε αναμονή δικαιολογητικών'), ('DECISION_PREPARATION', 'Ετοιμασία απόφασης'), ('PENDING_YC_COMMITTEE', 'Αναμονή απόφασης Υγειονομικής Επιτροπής'), ('PENDING_SIGNATURES', 'ΣΗΔΕ - προς υπογραφές'), ('COMPLETED', 'Ολοκληρώθηκε'), ('SUPERVISOR_REJECTED', 'Αρνητική έγκριση προϊσταμένου'), ('REJECTED_BY_LEAVES_DEPT', 'Απόρριψη από τμήμα αδειών'), ('CANCELLED_BY_APPLICANT', 'Ανάκληση από αιτούντα')], default='DRAFT', max_length=40, verbose_name='Κατάσταση'),
        ),
        migrations.CreateModel(
            name='YCCommitteeAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Γνώσης')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yc_acknowledged_by', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yc_acknowledgments', to=settings.AUTH_USER_MODEL, verbose_name='Χειριστής')),
            ],
            options={
                'verbose_name': 'Γνώση Υγειονομικής Επιτροπής',
                'verbose_name_plural': 'Γνώσεις Υγειονομικής Επιτροπής',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('handler', 'employee')},
            },
        ),
    ]
