# Generated by Django 5.2.3 on 2026-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0035_alter_leaverequest_status_yccommitteeacknowledgment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='merged_pdf_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Δημιουργίας Ενοποιημένου PDF'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='merged_pdf_encryption_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='Κλειδί Κρυπτογράφησης Ενοποιημένου PDF'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='merged_pdf_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Διαδρομή Ενοποιημένου PDF'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='merged_pdf_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αποστολής Email'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='merged_pdf_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Μέγεθος Ενοποιημένου PDF'),
        ),
    ]
