# Generated by Django 5.2.3 on 2026-05-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0036_leaverequest_merged_pdf_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_revocation',
            field=models.BooleanField(default=False, help_text='Αν είναι ενεργό, ο τύπος άδειας αφορά ανάκληση άδειας', verbose_name='Ανάκληση'),
        ),
    ]
