# Generated by Django 5.2.3 on 2026-05-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0037_leavetype_is_revocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days',
            field=models.PositiveIntegerField(default=1, help_text='Συνολικός αριθμός ημερών άδειας', verbose_name='Ημέρες Άδειας'),
        ),
    ]
