# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0038_leaverequest_days'),
    ]

    state_operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='requested_days',
            field=models.PositiveIntegerField(default=1, help_text='Συνολικός αριθμός ημερών άδειας που αιτείται ο χρήστης', verbose_name='Αιτούμενες Ημέρες Άδειας'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]