# Generated by Django 5.2.3 on 2026-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0040_deactivate_leave_επιμορφωσης'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='instructions',
            field=models.TextField(blank=True, help_text='Οδηγίες που εμφανίζονται στον αιτούντα κατά τη δημιουργία αίτησης', verbose_name='Οδηγίες'),
        ),
    ]
