# Generated by Django 5.2.3 on 2026-05-30 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0041_add_instructions_to_leavetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yccommitteeacknowledgment',
            options={'ordering': ['-acknowledged_at'], 'verbose_name': 'Γνωμάτευση Υγειονομικής Επιτροπής', 'verbose_name_plural': 'Γνώσεις Υγειονομικής Επιτροπής'},
        ),
        migrations.CreateModel(
            name='YearlySickLeaveTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Έτος')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='Σύνολο Ημερών')),
                ('is_locked', models.BooleanField(default=False, help_text='Αν είναι ενεργό, η εγγραφή δεν μπορεί να τροποποιηθεί', verbose_name='Κλειδωμένο')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_sick_leave_totals', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Ετήσιο Σύνολο Αναρρωτικών',
                'verbose_name_plural': 'Ετήσια Σύνολα Αναρρωτικών',
                'ordering': ['-year', 'employee__last_name', 'employee__first_name'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
