# Generated by Django 5.2.3 on 2026-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0043_fix_requested_days_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='counts_against_balance',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='general_category',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='id_adeias',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='name_simple',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='thematic_folder',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='requested_days',
            field=models.PositiveIntegerField(default=1, help_text='Συνολικός αριθμός ημερών άδειας που αιτείται ο χρήστης', verbose_name='Αιτούμενες Ημέρες Άδειας'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Πρόχειρη αίτηση'), ('SUBMITTED', 'Υποβληθείσα αίτηση'), ('PENDING_KEDASY_PROTOCOL', 'Εκκρεμεί Πρωτόκολλο ΚΕΔΑΣΥ/ΚΕΠΕΑ'), ('PENDING_PROTOCOL', 'Για πρωτόκολλο ΠΔΕΔΕ'), ('IN_REVIEW', 'Σε επεξεργασία από τμήμα αδειών'), ('WAITING_FOR_DOCUMENTS', 'Σε αναμονή δικαιολογητικών'), ('DECISION_PREPARATION', 'Ετοιμασία απόφασης'), ('PENDING_YC_COMMITTEE', 'Αναμονή απόφασης Υγειονομικής Επιτροπής'), ('PENDING_SIGNATURES', 'ΣΗΔΕ - προς υπογραφές'), ('COMPLETED', 'Ολοκληρώθηκε'), ('SUPERVISOR_REJECTED', 'Αρνητική έγκριση προϊσταμένου'), ('REJECTED_BY_LEAVES_DEPT', 'Απόρριψη από τμήμα αδειών'), ('CANCELLED_BY_APPLICANT', 'Ανάκληση από αιτούντα')], default='DRAFT', max_length=40, verbose_name='Κατάσταση'),
        ),
    ]
