# Generated by Django 5.2.3 on 2026-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0044_remove_leavetype_counts_against_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='max_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Μέγιστες Ημέρες'),
        ),
    ]
