# Generated by Django 5.2.3 on 2026-06-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0045_make_leavetype_max_days_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisiontemplate',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='decisiontemplate',
            name='workflow_variant',
        ),
        migrations.RemoveField(
            model_name='letterhead',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requiredattachmentrule',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='requiredattachmentrule',
            name='workflow_variant',
        ),
        migrations.DeleteModel(
            name='ApprovalRule',
        ),
        migrations.DeleteModel(
            name='DecisionTemplate',
        ),
        migrations.DeleteModel(
            name='Letterhead',
        ),
        migrations.DeleteModel(
            name='RequiredAttachmentRule',
        ),
        migrations.DeleteModel(
            name='WorkflowVariant',
        ),
    ]
