# Generated by Django 5.2.3 on 2026-06-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0046_remove_unused_letterhead_and_variant_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='regularleavebalanceentry',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='regularleavebalanceentry',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='regularleavebalanceentry',
            name='verified_by',
        ),
    ]
