# Generated by Django 5.2.3 on 2026-06-16

from django.db import migrations
from django.db.models import F


def backfill_submitted_at(apps, schema_editor):
    """Συμπλήρωση submitted_at από created_at για παλιές/μεταφερμένες εγγραφές."""
    LeaveRequest = apps.get_model('leaves', 'LeaveRequest')
    LeaveRequest.objects.filter(
        submitted_at__isnull=True,
    ).exclude(
        status='DRAFT',
    ).update(submitted_at=F('created_at'))


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0047_remove_unused_model_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_submitted_at, reverse_backfill),
    ]
