# Generated by Django 5.2.3 on 2026-07-23 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0051_documents_notification_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='regularleavebalanceentry',
            name='carryover_after',
            field=models.IntegerField(blank=True, help_text='Κουβάς προηγούμενου έτους μετά την κίνηση', null=True, verbose_name='Μεταφερόμενο Υπόλοιπο Μετά'),
        ),
        migrations.AddField(
            model_name='regularleavebalanceentry',
            name='current_after',
            field=models.IntegerField(blank=True, help_text='Κουβάς τρέχοντος έτους μετά την κίνηση', null=True, verbose_name='Τρέχον Υπόλοιπο Μετά'),
        ),
        migrations.AddField(
            model_name='regularleavebalanceentry',
            name='new_entitlement',
            field=models.IntegerField(blank=True, null=True, verbose_name='Νέες Δικαιούμενες'),
        ),
        migrations.AddField(
            model_name='regularleavebalanceentry',
            name='old_entitlement',
            field=models.IntegerField(blank=True, null=True, verbose_name='Παλιές Δικαιούμενες'),
        ),
        migrations.AlterField(
            model_name='regularleavebalanceentry',
            name='entry_type',
            field=models.CharField(choices=[('INITIAL_BALANCE', 'Αρχικό Υπόλοιπο'), ('LEAVE_GRANTED', 'Χορήγηση Κανονικής Άδειας'), ('LEAVE_REVOKED', 'Ανάκληση Άδειας'), ('MANUAL_ADJUSTMENT', 'Διοικητική Διόρθωση'), ('CARRYOVER_IMPORT', 'Μεταφορά Υπολοίπου'), ('PREVIOUS_YEAR_CORRECTION', 'Διόρθωση Προηγούμενου Έτους'), ('ADMIN_CORRECTION', 'Διόρθωση Χειριστή'), ('ENTITLEMENT_CHANGE', 'Αλλαγή Δικαιούμενων Ημερών'), ('ANNUAL_GRANT', 'Ετήσια Χορήγηση Δικαιώματος'), ('CARRYOVER_EXPIRE', 'Λήξη Παλαιού Υπολοίπου')], max_length=30, verbose_name='Τύπος Κίνησης'),
        ),
        migrations.CreateModel(
            name='BalanceRenewalSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_year', models.PositiveIntegerField(unique=True, verbose_name='Έτος που κλείνει')),
                ('warning_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Άνοιγμα προειδοποίησης')),
                ('handlers_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Ειδοποίηση χειριστών')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Εφαρμογή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_balance_renewals', to=settings.AUTH_USER_MODEL, verbose_name='Εφαρμόστηκε από')),
            ],
            options={
                'verbose_name': 'Σεζόν Ετήσιας Ανανέωσης',
                'verbose_name_plural': 'Σεζόνες Ετήσιας Ανανέωσης',
                'ordering': ['-closing_year'],
            },
        ),
        migrations.CreateModel(
            name='BalanceRenewalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_month', models.PositiveSmallIntegerField(default=12, verbose_name='Μήνας προειδοποίησης')),
                ('warning_day', models.PositiveSmallIntegerField(default=15, verbose_name='Ημέρα προειδοποίησης')),
                ('apply_month', models.PositiveSmallIntegerField(default=1, verbose_name='Μήνας εφαρμογής')),
                ('apply_day', models.PositiveSmallIntegerField(default=1, verbose_name='Ημέρα εφαρμογής')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='Υπενθυμίσεις χειριστή')),
                ('reminder_interval_days', models.PositiveSmallIntegerField(default=3, verbose_name='Διάστημα υπενθύμισης (ημέρες)')),
                ('target_type_codes', models.CharField(default='ADMINISTRATIVE,EDUCATIONAL', help_text='Διαχωρισμός με κόμμα, π.χ. ADMINISTRATIVE,EDUCATIONAL', max_length=255, verbose_name='Κωδικοί τύπων υπαλλήλων')),
                ('user_message_template', models.TextField(default='Αγαπητέ/ή {full_name},\n\nΣας ενημερώνουμε ότι κατά την ετήσια ανανέωση κανονικών αδειών ({apply_date}) θα λήξουν {expiring_days} ημέρες που προέρχονται από παλαιότερα έτη ({expiring_years}).\nΤο υπόλοιπο του αμέσως προηγούμενου έτους ({carryover_days} ημέρες), εφόσον υπάρχει, θα μεταφερθεί.\n\nΓια διευκρινίσεις επικοινωνήστε με το Τμήμα Αδειών.', verbose_name='Πρότυπο μηνύματος χρηστών')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
            ],
            options={
                'verbose_name': 'Ρυθμίσεις Ετήσιας Ανανέωσης',
                'verbose_name_plural': 'Ρυθμίσεις Ετήσιας Ανανέωσης',
            },
        ),
        migrations.CreateModel(
            name='BalanceRenewalUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiring_days', models.PositiveIntegerField(default=0, verbose_name='Ημέρες προς λήξη')),
                ('carryover_days', models.PositiveIntegerField(default=0, verbose_name='Υπόλοιπο προηγ. έτους')),
                ('entitlement_days', models.PositiveIntegerField(default=0, verbose_name='Νέο δικαίωμα')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Ενημερώθηκε')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Εφαρμόστηκε')),
                ('apply_error', models.TextField(blank=True, verbose_name='Σφάλμα εφαρμογής')),
                ('notified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_balance_renewal_notices', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='leaves.balancerenewalseason', verbose_name='Σεζόν')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_renewal_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Κατάσταση Ανανέωσης Χρήστη',
                'verbose_name_plural': 'Καταστάσεις Ανανέωσης Χρηστών',
                'ordering': ['user__last_name', 'user__first_name'],
                'unique_together': {('season', 'user')},
            },
        ),
    ]
