# Generated by Django 5.2.3 on 2026-07-23 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0052_balance_renewal_phase_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularleavebalanceentry',
            name='entry_type',
            field=models.CharField(choices=[('INITIAL_BALANCE', 'Αρχικό Υπόλοιπο'), ('LEAVE_GRANTED', 'Χορήγηση Κανονικής Άδειας'), ('LEAVE_REVOKED', 'Ανάκληση Άδειας'), ('MANUAL_ADJUSTMENT', 'Διοικητική Διόρθωση'), ('CARRYOVER_IMPORT', 'Μεταφορά Υπολοίπου'), ('PREVIOUS_YEAR_CORRECTION', 'Διόρθωση Προηγούμενου Έτους'), ('ADMIN_CORRECTION', 'Διόρθωση Χειριστή'), ('ENTITLEMENT_CHANGE', 'Αλλαγή Δικαιούμενων Ημερών'), ('ANNUAL_GRANT', 'Ετήσια Χορήγηση Δικαιώματος'), ('CARRYOVER_EXPIRE', 'Λήξη Παλαιού Υπολοίπου'), ('CONTRACT_END_ZERO', 'Μηδενισμός Λήξης Σύμβασης'), ('CONTRACT_GRANT', 'Χορήγηση Νέας Σύμβασης')], max_length=30, verbose_name='Τύπος Κίνησης'),
        ),
        migrations.CreateModel(
            name='SubstituteContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start', models.DateField(verbose_name='Έναρξη σύμβασης')),
                ('contract_end', models.DateField(verbose_name='Λήξη σύμβασης')),
                ('entitled_days', models.PositiveIntegerField(default=0, verbose_name='Δικαιούμενες ημέρες')),
                ('opening_balance', models.PositiveIntegerField(default=0, verbose_name='Αρχικό υπόλοιπο')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ενεργή'), ('ENDED', 'Έληξε'), ('SUPERSEDED', 'Αντικαταστάθηκε')], default='ACTIVE', max_length=20, verbose_name='Κατάσταση')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία κλεισίματος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_substitute_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_substitute_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Έληξε από')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Σύμβαση Αναπληρωτή',
                'verbose_name_plural': 'Συμβάσεις Αναπληρωτών',
                'ordering': ['-contract_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubstituteContractSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_end_month', models.PositiveSmallIntegerField(default=6, verbose_name='Μήνας προεπιλογής λήξης')),
                ('default_end_day', models.PositiveSmallIntegerField(default=30, verbose_name='Ημέρα προεπιλογής λήξης')),
                ('target_type_codes', models.CharField(default='SUBSTITUTE', help_text='Διαχωρισμός με κόμμα, π.χ. SUBSTITUTE', max_length=255, verbose_name='Κωδικοί τύπων υπαλλήλων')),
                ('opening_balance_policy', models.CharField(choices=[('entitlement', 'Ίσο με δικαιούμενες'), ('zero', 'Μηδέν'), ('manual_only', 'Μόνο χειροκίνητα')], default='entitlement', max_length=20, verbose_name='Πολιτική αρχικού υπολοίπου')),
                ('end_user_message', models.TextField(default='Η σύμβασή σας έληξε και το υπόλοιπο κανονικών αδειών μηδενίστηκε. Για νέα περίοδο απασχόλησης θα ενημερωθείτε αφού το Τμήμα Αδειών καταχωρήσει τη νέα σύμβαση.', verbose_name='Μήνυμα χρήστη στη λήξη')),
                ('activate_user_message', models.TextField(default='Καταχωρήθηκε η νέα σας σύμβαση. Μπορείτε πλέον να υποβάλετε αιτήσεις άδειας.', verbose_name='Μήνυμα χρήστη στη νέα σύμβαση')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ενημερώθηκε από')),
            ],
            options={
                'verbose_name': 'Ρυθμίσεις Συμβάσεων Αναπληρωτών',
                'verbose_name_plural': 'Ρυθμίσεις Συμβάσεων Αναπληρωτών',
            },
        ),
    ]
