# Generated by Django 5.2.3 on 2026-07-23 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0053_substitute_contracts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='protocol_email_failed_at',
            field=models.DateTimeField(blank=True, help_text='Συμπληρώνεται όταν αποτύχει η αυτόματη αποστολή PDF στο πρωτόκολλο κατά την υποβολή', null=True, verbose_name='Αποτυχία Αυτόματης Αποστολής Email Πρωτοκόλλου'),
        ),
        migrations.CreateModel(
            name='ProtocolEmailFailureAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Γνώσης')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_email_failure_acknowledgments', to=settings.AUTH_USER_MODEL, verbose_name='Χειριστής')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_email_failure_acknowledgments', to='leaves.leaverequest', verbose_name='Αίτηση Άδειας')),
            ],
            options={
                'verbose_name': 'Γνώση Αποτυχίας Email Πρωτοκόλλου',
                'verbose_name_plural': 'Γνώσεις Αποτυχίας Email Πρωτοκόλλου',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('leave_request', 'handler')},
            },
        ),
    ]
