# Generated by Django 5.0.1 on 2025-06-21 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος')),
                ('message', models.TextField(verbose_name='Μήνυμα')),
                ('notification_type', models.CharField(choices=[('info', 'Πληροφορία'), ('success', 'Επιτυχία'), ('warning', 'Προειδοποίηση'), ('error', 'Σφάλμα')], default='info', max_length=10, verbose_name='Τύπος')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Αναγνώστηκε')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ανάγνωσης')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Ειδοποίηση',
                'verbose_name_plural': 'Ειδοποιήσεις',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
